<?
// Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . '<a href="' . $this->url("home") . '">' . $this->transEsc("Homepage") . '</a> </li>';
  $this->layout()->breadcrumbs .= '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
  ?>


  <div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>

    </div>


    <a name="tabnav"></a>
    <div class="record-tabs">

      <ul class="nav nav-tabs">
	<? foreach ($this->tabs as $tab => $obj): ?>

	  <? // add current tab to breadcrumbs if applicable:
	    $desc = $obj->getDescription();
	    $tab_classes = array();
	    if (0 === strcasecmp($this->activeTab, $tab)) {
	      if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
		$tab_classes[] = 'active';
	      }
	      $tab_classes[] = 'initiallyActive';
	      $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
	      $activeTabObj = $obj;
	    }
	    if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
	    if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
	  ?>
	  <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
	    <a class="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
	  </li>
	<? endforeach; ?>
      </ul>


      <? if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
        <div class="tab-pane active <?=$this->activeTab ?>-tab">
	  <div class="tab-content">
	  <?=$this->record($this->driver)->getTab($this->tabs['Details'])?>
	  </div>
        </div>
      <? endif; ?>
    </div>
  </div>
