<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // $this->headScript()->appendScript("obalky.process", 'text/javascript', array());
  $this->headScript()->appendScript(
    'var permalink = "http://vufind.lib.cas.cz/Record/' . $this->driver->getUniqueId() . '";
     var bibinfo = { authors: [] };
     bibinfo["isbn"] = "' . $this->driver->getCleanISBN() . '";
     bibinfo["issn"] = "' . $this->driver->getCleanISSN() . '";
     obalky.process("obalky_display_knav","obalka_nahled", permalink, bibinfo);'
  );

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . '<a href="' . $this->url("home") . '">' . $this->transEsc("Homepage") . '</a> </li>';
  $this->layout()->breadcrumbs .= '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>

    <? //if ((count($this->tabs) > 0) && ($this->driver->getSourceIdentifier() != 'EDS') ): ?>
    <? if (count($this->tabs) > 0) : ?>
      <a name="tabnav"></a>
      <div class="record-tabs">
        <ul class="nav nav-tabs">
          <? foreach ($this->tabs as $tab => $obj): ?>

            <? // add current tab to breadcrumbs if applicable:
              $desc = $obj->getDescription();
              $tab_classes = array();
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  $tab_classes[] = 'active';
                }
                $tab_classes[] = 'initiallyActive';
                $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
              if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
            ?>
            <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
              <a class="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
            </li>
          <? endforeach; ?>
        </ul>

        <div class="tab-content">
          <? if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div class="tab-pane active <?=$this->activeTab ?>-tab">
              <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
            </div>
          <? endif; ?>
        </div>
      </div>
    <? endif; ?>

  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
  </div>
</div>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>
