<? $this->headLink()->appendStylesheet('EDS.css'); ?>
<?
    $items = $this->driver->getItems();
    $dbLabel = $this->driver->getDbLabel();
    $thumb = $this->driver->getThumbnail('medium');
    $pubType = $this->driver->getPubType();
    $customLinks = $this->driver->getCustomLinks();
    $accessLevel = $this->driver->getAccessLevel();
    $restrictedView = empty($accessLevel) ? false : true;
    $dbID  =  $this->driver->getDbID(); 
    $an  =  $this->driver->getAn(); 
    $publishYear = $this->driver->getPublishYear();
    $identifiers = $this->driver->getIdentifiers();
    $knavID = $this->driver->getKnavID();
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <? if ($thumb): ?>
        <img src="<?=$this->escapeHtmlAttr($thumb)?>" class="recordcover" alt="<?=$this->transEsc('Cover Image')?>"/>
    <? else: ?>
      <div class="clearfix">
        <span class="recordcover pt-icon pt-<?=$this->driver->getPubTypeId()?>"></span>
      </div>
    <? endif; ?>
    <? if ($pubType): ?>
      <p><?=$this->transEsc($pubType)?></p>
    <? endif; ?>

    <div class="external-links">
      <? $pLink = $this->driver->getPLink();
          if($pLink): ?>
        <span>
          <a href="<?=$this->escapeHtmlAttr($pLink)?>">
            <?=$this->transEsc('View in EDS')?>
          </a>
        </span><br />
      <? endif; ?>
      <? $pdfLink = $this->driver->getPdfLink();
          if ($pdfLink): ?>
        <span>
          <a href="<?=$pdfLink?>" class="icon pdf fulltext">
            <?=$this->transEsc('PDF Full Text')?>
          </a>
        </span><br />
      <? endif; ?>
      <? if ($this->driver->hasHTMLFullTextAvailable()): ?>
        <span>
          <a href="<?=$this->recordLink()->getUrl($this->driver, 'fulltext')?>#html" class="icon html fulltext">
            <?=$this->transEsc('HTML Full Text')?>
          </a>
        </span><br />
      <? endif; ?>
    </div>
  </div>
  <div class="col-sm-9">
    <h3 property="name"><?=$this->driver->getTitle()?></h3>

    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $betterItems = array(); ?>
      <?  foreach ($items as $item):
          $betterItems[$item['Label']][] = $item['Data'];
        endforeach; ?>

      <!-- <? foreach ($items as $key => $item): ?>
        <? if (!empty($item['Data'])): ?>
        <tr>
          <th><?=$this->transEsc($item['Label'])?>:</th>
          <td><?=$this->driver->linkUrls($item['Data'])?></td>
        </tr>
        <? endif; ?>
      <? endforeach; ?> -->

      <? if (!empty($betterItems['Authors'])) : ?>
        <tr>
          <th><?=$this->transEsc('Author')?>:</th>
          <td><?=$betterItems['Authors'][0]?></td>
        </tr>
      <? endif; ?>
      <? if (!empty($betterItems['Other Authors'])) : ?>
        <tr>
          <th><?=$this->transEsc('Other authors')?>:</th>
          <td>
            <? foreach ($betterItems['Other Authors'] as $otherAut): ?>
              <div>
                <?=$otherAut?>
              </div>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
      <? if (!empty($betterItems['Contributors'])) : ?>
        <tr>
          <th><?=$this->transEsc('Contributors')?>:</th>
          <td><?=$betterItems['Contributors'][0]?></td>
        </tr>
      <? endif; ?>
      <? if (!empty($betterItems['Language'])) : ?>
        <tr>
          <th><?=$this->transEsc('Language')?>:</th>
          <td><?=$betterItems['Language'][0]?></td>
        </tr>
      <? endif; ?>
      <? if (!empty($betterItems['Publication Information'])) : ?>
        <tr>
          <th><?=$this->transEsc('Published')?>:</th>
          <td><?=$betterItems['Publication Information'][0]?></td>
        </tr>
      <? endif; ?>
      <? if (!empty($betterItems['Source'])) : ?>
        <tr>
          <th><?=$this->transEsc('Source')?>:</th>
          <td><?=$betterItems['Source'][0]?></td>
        </tr>
      <? endif; ?>
      <? if (!empty($publishYear)) : ?>
        <tr>
          <th><?=$this->transEsc('Published')?>:</th>
          <td><?=$publishYear?></td>
        </tr>
      <? endif; ?>  
      <? if (!empty($betterItems['ISSN'])) : ?>
        <tr>
          <th><?=$this->transEsc('ISSN')?>:</th>
          <td><?=$betterItems['ISSN'][0]?></td>
        </tr>
      <? elseif (!empty($identifiers['issn'])) : ?>
        <tr>
          <th><?=$this->transEsc('ISSN')?>:</th>
          <td><?=$identifiers['issn']?></td>
        </tr>
      <? endif; ?> 
      <? if (!empty($betterItems['Subject Terms'])) : ?>
        <tr>
          <th><?=$this->transEsc('Subject')?>:</th>
          <td>
            <? foreach ($betterItems['Subject Terms'] as $subject): ?>
              <div>
                <?=$subject?>
              </div>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
      <? if (!empty($betterItems['Description'])) : ?>
        <tr>
          <th><?=$this->transEsc('Description')?>:</th>
          <td><?=$betterItems['Description'][0]?></td>
        </tr>
      <? endif; ?>
      <? if (!empty($betterItems['Abstract'])) : ?>
        <tr>
          <th><?=$this->transEsc('Abstract')?>:</th>
          <td><?=$betterItems['Abstract'][0]?></td>
        </tr>
      <? endif; ?>
      <? if (!empty($an)) : ?>
        <tr>
          <th><?=$this->transEsc('Accession number')?>:</th>
          <td><?=$an?></td>
        </tr>
      <? endif; ?>
      <? if ($dbLabel): ?>
        <tr>
          <th><?=$this->transEsc('Database')?>:</th>
          <td><?=$this->escapeHtml($dbLabel)?></td>
        </tr>
      <? endif; ?>


      <? $betterLinks = $this->driver->getOnlineLinks(); ?>
      <? if ((!empty($betterItems['Availability'])) || (!empty($customLinks)) || (!empty($betterLinks))) : ?>
        <tr class="resultItemLine4 custom-links">
          <th><?=$this->transEsc('Online access')?>:</th>
          <td>
            <? if (!empty($betterLinks)) : ?>
              <? foreach ($betterLinks as $key => $value): ?>
                <div>
                   <a href="<?=$value['link'] ?>"><?=$value['text']?></a>
                </div>
              <? endforeach; ?>
            <? endif; ?>
            <? if (!empty($betterItems['Availability'])) : ?>              
                <div><a href="<?= $betterItems['Availability'][0] ?>"><?= $betterItems['Availability'][0] ?></a></div>
            <? endif; ?>   

            <? $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
            if (!empty($customLinks)): ?>
                <? foreach ($customLinks as $customLink): ?>
                  <? if ($customLink['Name'] == 'SFX Link Resolver (journal content)'): ?>
                    <? $url = isset($customLink['Url']) ? $customLink['Url'] : '';
                        $mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
                        $icon = isset ($customLink['Icon']) ? $customLink['Icon'] : '';
                        // $name = isset($customLink['Text']) ? $customLink['Text'] : '';
                        $name = "";
                    ?>
                    <div>
                      <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$this->escapeHtmlAttr($mot)?>" class="custom-link">
                        <? if ($icon): ?><img src="<?=$this->escapeHtmlAttr($icon)?>" /> <? endif; ?><?=$this->escapeHtml($name)?>
                      </a>
                    </div>
                  <? endif; ?>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->driver->isCatalog()): ?>
        <tr>
          <th><?=$this->transEsc('Catalog link');?>:</th>
          <td><a href="<?=$this->driver->getCatalogLink();?>"><?=$this->transEsc('Full view');?></a></td>
        </tr>

        <? if (!empty($betterItems['Publication Date'])) : ?>
          <? $pubDate = $betterItems['Publication Date'][0];?>
          <? if (($pubDate>0) && ($pubDate < (date("Y") - 100))  && is_numeric($pubDate)): ?>
            <tr>
              <td colspan=2>
              <a href="http://books2ebooks.eu/odm/orderformular.do?formular_id=201&lang=cz&sys_id=<?=$knavID?>" target="_blank"><img src="/themes/knav/images/eod_button.gif" alt="EOD"></a>
              </td>
            </tr>
          <? endif;?>
        <? endif; ?>

      <? endif; ?>
      
      <?if ($this->driver->hasHTMLFullTextAvailable() && !$restrictedView):
          $fullText = $this->driver->getHtmlFullText();?>
        <tr id="html">
          <td colspan="2">
            <?=$fullText?>
          </td>
        </tr>
      <? elseif ($this->driver->hasHTMLFullTextAvailable() && $restrictedView): ?>
        <tr id="html">
          <td>
            <?=$this->transEsc('Full text is not displayed to guests')?>
          </td>
          <td>
            <a class="login" href="<?=$this->url('myresearch-home')?>" rel="nofollow">
              <strong><?=$this->transEsc('Login for full access')?></strong>
            </a>
          </td>
        </tr>
      <? endif; ?>

    </table>
  </div>
</div>
