<? $account = $this->auth()->getManager(); ?>
<div class="navbar-header">
  <!-- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-bars"></i>
  </button> -->
<!--   <strong><a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="https://knihoveda.cz" target="_blank">Knihověda.cz</a></strong> -->
  <a href="https://knihoveda.cz" target="_blank" class="navbar-brand" title="Knihověda.cz">
    <img class="logo_image" src="/themes/knihoveda/images/logo_kvo.svg" alt="Knihověda.cz">
  </a>
</div>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <nav>
      <ul class="nav navbar-nav navbar-right flip">
	<li>
          <a href="<?=$this->url('alphabrowse-home') ?>"><?=$this->transEsc("Indexes")?></a>
        </li>
        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <? endif; ?>
        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
          <? if ($account->isLoggedIn()): ?>
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home"></i> <?= $account->isLoggedIn()->lastname ?> <?= $account->isLoggedIn()->firstname ? $account->isLoggedIn()->firstname : '' ?></a>
            </li>
          <? endif; ?>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
          </li>
          <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
            <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
            <? else: ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
            <? endif; ?>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="theme dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="language dropdown">
            <form method="post" name="langForm" id="langForm">
              <input type="hidden" name="mylang"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>
      </ul>
    </nav>
  </div>
<? endif; ?>
<? if ($this->layout()->searchbox !== false): ?>
  <section class="visible-lg">
    <?=$this->layout()->searchbox ?>
  </section>
<? endif; ?>
