<?
    // Set up page title:
    $this->headTitle($this->translate('Loan history'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Loan history') . '</li>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Loan history')?></h2>
    <?=$this->flashmessages()?>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

    <? if (!empty($this->transactions)): ?>

      <? if ($paginator): ?>
        <?=$this->transEsc("Showing")?>
        <? $start = $paginator->getAbsoluteItemNumber(1);
           $end = $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage());
           $total = $paginator->getTotalItemCount();
        ?>
        <strong><?=$this->localizedNumber($start)?></strong> - <strong><?=$this->localizedNumber($end > $total ? $total : $end)?></strong>
        <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($total)?></strong>
      <? endif; ?>

      <? $i = 0; foreach ($this->transactions as $resource): ?>
        <hr/>
        <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row">

          <? $cover = $this->record($resource)->getCover('checkedout', 'small'); ?>
          <? if ($cover): ?>
            <div class="col-sm-2 col-xs-11 text-center">
            <? /* Display thumbnail if appropriate: */ ?>
              <?=$cover?>
            </div>

            <div class="col-sm-8 col-xs-12">
         <? else: ?>
            <div class="col-sm-9">
         <? endif; ?>

            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource) .
                  '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>
            <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
              <?=str_replace('class="', 'class="label label-info ', $this->record($resource)->getFormatList())?>
              <br/>
            <? endif; ?>
            <? if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], array(), $ilsDetails['institution_name'])?></strong>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], array(), $ilsDetails['borrowingLocation'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['loandate'])): ?>
              <strong><?=$this->transEsc('Loan date')?>:</strong> <?=$this->escapeHtml($ilsDetails['loandate']); ?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['duedate'])): ?>
              <strong><?=$this->transEsc('Due Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['duedate']); ?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['lastRenew'])): ?>
              <strong><?=$this->transEsc('Last extension date')?>:</strong> <?=$this->escapeHtml($ilsDetails['lastRenew']); ?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['renewCount']) and ($ilsDetails['renewCount'] != '0')): ?>
              <strong><?=$this->transEsc('Number of extensions')?>:</strong> <?=$this->escapeHtml($ilsDetails['renewCount']); ?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['returned'])): ?>
              <strong><?=$this->transEsc('Return date')?>:</strong> <?=$this->escapeHtml($ilsDetails['returned']); ?>
              <br />
            <? endif; ?>

            <? if (($ilsDetails['fine'] != '') and ($ilsDetails['fine'] != '0') ): ?>
              <strong><?=$this->transEsc('Fee')?>:</strong> <?=$this->escapeHtml($ilsDetails['fine']); ?>
              <br />
            <? endif; ?>


            <? $showStatus = true; ?>

            <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <? endif; ?>

          </div>
        </div>
      <? endforeach; ?>
 
      <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
    <? else: ?>
      <?=$this->transEsc('You do not have any history loans')?>.
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'history'))?>
  </div>
</div>
